apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfi-tcscc-koost-morning
  labels:
    app: pfi-tcscc-koost-morning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pfi-tcscc-koost-morning
  template:
    metadata:
      labels:
        app: pfi-tcscc-koost-morning
    spec:
      containers:
        - name: pfi-tcscc-koost-morning
          image: gcr.io/pfi-tcscc-koost-nature/pfi-tcscc-koost-morning:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
