apiVersion: v1
kind: Service
metadata:
  name: pfi-tcscc-koost-morning-service
spec:
  type: LoadBalancer
  selector:
    app: pfi-tcscc-koost-morning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
